package com.example.mydemo.bean;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.mydemo.bean.Quan;

import com.example.mydemo.bean.QuanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig quanDaoConfig;

    private final QuanDao quanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        quanDaoConfig = daoConfigMap.get(QuanDao.class).clone();
        quanDaoConfig.initIdentityScope(type);

        quanDao = new QuanDao(quanDaoConfig, this);

        registerDao(Quan.class, quanDao);
    }
    
    public void clear() {
        quanDaoConfig.getIdentityScope().clear();
    }

    public QuanDao getQuanDao() {
        return quanDao;
    }

}
