package com.example.mydemo.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table QUAN.
 */
public class Quan {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String name_mon;
    private int gia;
    /** Not-null value. */
    private String diachi;
    /** Not-null value. */
    private String img_mon;
    private Integer lat;
    private Integer lon;
    private Integer like;
    private Integer unlike;
    private Integer hienthi;
    private Integer sdt;
    private Integer oder;
    private Integer den;

    public Quan() {
    }

    public Quan(Long id) {
        this.id = id;
    }

    public Quan(Long id, String name, String name_mon, int gia, String diachi, String img_mon, Integer lat, Integer lon, Integer like, Integer unlike, Integer hienthi, Integer sdt, Integer oder, Integer den) {
        this.id = id;
        this.name = name;
        this.name_mon = name_mon;
        this.gia = gia;
        this.diachi = diachi;
        this.img_mon = img_mon;
        this.lat = lat;
        this.lon = lon;
        this.like = like;
        this.unlike = unlike;
        this.hienthi = hienthi;
        this.sdt = sdt;
        this.oder = oder;
        this.den = den;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getName_mon() {
        return name_mon;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName_mon(String name_mon) {
        this.name_mon = name_mon;
    }

    public int getGia() {
        return gia;
    }

    public void setGia(int gia) {
        this.gia = gia;
    }

    /** Not-null value. */
    public String getDiachi() {
        return diachi;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }

    /** Not-null value. */
    public String getImg_mon() {
        return img_mon;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImg_mon(String img_mon) {
        this.img_mon = img_mon;
    }

    public Integer getLat() {
        return lat;
    }

    public void setLat(Integer lat) {
        this.lat = lat;
    }

    public Integer getLon() {
        return lon;
    }

    public void setLon(Integer lon) {
        this.lon = lon;
    }

    public Integer getLike() {
        return like;
    }

    public void setLike(Integer like) {
        this.like = like;
    }

    public Integer getUnlike() {
        return unlike;
    }

    public void setUnlike(Integer unlike) {
        this.unlike = unlike;
    }

    public Integer getHienthi() {
        return hienthi;
    }

    public void setHienthi(Integer hienthi) {
        this.hienthi = hienthi;
    }

    public Integer getSdt() {
        return sdt;
    }

    public void setSdt(Integer sdt) {
        this.sdt = sdt;
    }

    public Integer getOder() {
        return oder;
    }

    public void setOder(Integer oder) {
        this.oder = oder;
    }

    public Integer getDen() {
        return den;
    }

    public void setDen(Integer den) {
        this.den = den;
    }

}
